#!/bin/bash

# Copy the project tar
cd /mnt/documents-smb/Alan\'s\ Server/Projects/Software/Web/Mogul\ Frameworks/Mogul\ MVC/Framework/
tar cfvz Mogul.tar.gz application/ framework/ .htaccess index.php
rm /mnt/documents-smb/Alan\'s\ Server/Projects/Software/Web/Mogul\ Frameworks/Mogul\ MVC/Tools/resource/*
mv Mogul.tar.gz /mnt/documents-smb/Alan\'s\ Server/Projects/Software/Web/Mogul\ Frameworks/Mogul\ MVC/Tools/resource/

# Rename the perl files
cp src/mogul-controller.pl bin/mogul-controller
cp src/mogul-git-empty.pl bin/mogul-git-empty
cp src/mogul-icon.pl bin/mogul-icon
cp src/mogul-model-ar.pl bin/mogul-model-ar
cp src/mogul-model-pdo.pl bin/mogul-model-pdo
cp src/mogul-project.pl bin/mogul-project
cp src/mogul-vo.pl bin/mogul-vo

# Make the executable
chmod 777 bin/*