#!/usr/bin/perl

use Term::ANSIColor;

#Add .gitempty files to empty folders
system('find . -type d -empty -exec touch {}/.gitempty \;');

print color 'green';
print "Complete\n";
print color 'reset';